server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: 192.168.142.128:9092,192.168.142.128:9093,192.168.142.128:9094
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
#  redis:
#    host: 192.168.142.128


#logging:
#  level:
#    root: info

